### ISSUE TITLE
Diplication URL dans les adresses

### ISSUE THREAD

**Issue by ostrowskiex** [ansforge/IG-fhir-repertoire-offre-ressources-sante#86]
Bonjour,

en lisant la spécification RORFHIR j'ai remarqué un petit soucis au niveau des Adresses de l'organisation ROR

Pour les champs [streetNameBase] et [streetNameHamlet] on la même url de référence : est-ce normal ?
URL : http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetNameBase 

Pour streetNameHamlet on ne devrait pas plutot avoir une url sous la forme base/iso21090-ADXP-streetNameHamlet ?

**Comment by nriss** [comment]
Bonjour, le problème est que cette extension n'est pas définie en FHIR, raison pour laquelle nous avons fait le choix d'utiliser deux fois la même extension.
Voyez-vous un problème à utiliser deux fois la même ?

**Comment by ostrowskiex** [comment]
Le soucis d'avoir la même extension c'est que cela ne nous permet pas de distinguer les deux champs.
Du coup j'ai un peu de mal a voir comment distinguer l'un ou l'autre.

**Comment by nriss** [comment]
Ok!
Je pense donc qu'il vaut mieux créer une nouvelle extension adresse-lieu-dit

https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/d84bd6aa1e01651b3d20cd31fa7cfcc453fe7d56/input/fsh/profiles/ROROrganization.fsh#L144C1-L144C33

**Comment by sly-kereval** [comment]
Sujet déjà abordé ici : #34

**Comment by paulineheurtebise** [comment]
Deux solutions donc s'offre à nous je pense : 
1. On créé une extension pour adresse-lieu-dit comme proposé par Nicolas
2. On applique la solution proposée dans #34 avec des id 

Quelle solution devons-nous mettre en œuvre ? 
Merci !

**Comment by nriss** [comment]
Merci d'avoir fait le lien entre les deux issues @paulineheurtebise ! 
Qu'en pensez-vous ?

Selon moi:
- L'id est intéressant car les dev sont partis dans cette direction
- Créer une nouvelle extension est peut être plus propre étant donné que le discriminator est l'url et dont que l'on arrive pas à distinguer les deux slices avec le discriminator


Y-a-t'il une solution pour modifier le discriminator pour prendre en compte l'id + l'url ?

**Comment by paulineheurtebise** [comment]
Merci Nicolas pour cette proposition, je ne suis pas sûre de bien comprendre, tu penses que nous devrions prendre en compte les 2 solutions ? 

1. Si on met en place l'id 
=> Nous devons mettre en place comme discriminateur id + url (ce qui semble possible avec l'exemple que tu nous avais fourni il y a quelques mois https://www.hl7.org/fhir/bp.profile.json.html) 
=> Moins d'impact pour le développement s'ils sont partis dans cette direction ? 

2. Si on créé une nouvelle extension
=> Nous pouvons garder le même discriminateur 

J'ai l'impression que soit on met en place la solution 1 soit la solution 2.

**Comment by nriss** [comment]
Oui c'est soit l'une soit l'autre, je n'ai pas d'avis fort sur la solution à privilégier :)

**Comment by sdemeyANS** [comment]
donc la solution 1 aurait moins d'impact pour ce qui a déjà été implémenté? cf #34

**Comment by sdemeyANS** [comment]
@jcserafini ok pour toi?

**Comment by paulineheurtebise** [comment]
Atelier 06/09 : 
o	L’idéal est de choisir la solution qui a le moins d’impact possible. 
o	Solution avec l’id retenue car nous avons une cardinalité en 0..1
o	Il faut vérifier que nous pouvons modifier le slice pour prendre l’id + url et dans ces cas là pas d’impacts sur les dev

**Comment by paulineheurtebise** [comment]
Après nombreuses recherches, le dernier commit que nous avons fait contient le slice avec 2 discriminateurs : id + url. 
Sur ce commit on trouve une erreur au moment du run de IG publisher. 
Après demande à la communauté FHIR (https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Extension.20slicing.20causes.20IG.20publisher.20error) ce n'est pas un bug connu. 

L'option de faire un sous - slice est possible mais le discriminateurs utilisés dans le sous - slice doit être déclaré dans le slice d'origine. Donc l'id ne peut pas etre déclaré uniquement au moment du sous-slice. (idem cf réponse de Grahame sur https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Reslicing.20extensions.20causes.20validator.20errors)  

Dans l'écriture dans les fsh, il est possible d'écrire uniquement en discriminateur id ou id+url.
Dans le cas des extensions, le slice est natif sur les url, il est donc pas nécessaire de l'écrire.

**Comment by paulineheurtebise** [comment]
Pour compléter les travaux, nous avons essayé de créer le snapshot de la SD dans FHIR validator en préprod. 
FHIR Validator arrive bien à créer le snapshot, cependant il est pas sur la dernière version HAPI.

**Comment by paulineheurtebise** [comment]
Atelier 16/10 : chercher dans les extensions HL7 une qui pourrait correspondre au besoin afin d'éviter le slice avec 2 discriminateurs.

**Comment by paulineheurtebise** [comment]
Proposition pour le lieu dit : 

- utiliser l'extension [precinct](http://hl7.org/fhir/extensions/StructureDefinition-iso21090-ADXP-precinct.html#root) : A subsection of a municipality. 
--> C'est plus proche de la définition de circonscription que de lieu-dit mais c'est pas aberrant non je pense
Ou
- créer une extension 


En synthèse pour l'adresse : 

- pointRemise
  - Définition ME : Lieu où le destinataire prend possession de son courrier. 
  - Extension [careOf](http://hl7.org/fhir/extensions/StructureDefinition-iso21090-ADXP-careOf.html#root) : name of the party who will take receipt at the specified address, and will take on responsibility for ensuring delivery to the target recipient.
- complementPointGeographique
  - Définition ME : Un complément de l'adresse au point géographique 
  - Extension [additionalLocator](http://hl7.org/fhir/extensions/StructureDefinition-iso21090-ADXP-additionalLocator.html#root) : This can be a unit designator, such as apartment number, suite number, or floor. There may be several unit designators in an address (e.g., “3rd floor, Appt. 342”). This can also be a designator pointing away from the location, rather than specifying a smaller location within some larger one (e.g., Dutch “t.o.” means “opposite to” for house boats located across the street facing houses).
- numeroVoie 
  - Définition ME : Un numéro dans la voie; dans les cas de numérotation sans extension, il est composé de 0 à 4 caractères numériques au maximum.
  - Extension [houseNumber ](http://hl7.org/fhir/extensions/StructureDefinition-iso21090-ADXP-houseNumber.html#root) : The number of a building, house or lot alongside the street. Also known as “primary street number”. This does not number the street but rather the building.
- extension 
  - Définition ME : Extension ou indice de répétition : mention bis, ter, quater, ...ou une lettre A, B, C, D, etc. lorsque ce caractère complète une numérotation de voirie.
  - Extension [buildingNumberSuffix](http://hl7.org/fhir/extensions/StructureDefinition-iso21090-ADXP-buildingNumberSuffix.html#root) : Any alphabetic character, fraction or other text that may appear after the numeric portion of a building number.
- typeVoie
  - Définition ME : Type de voie : rue, avenue, boulevard, etc. Attribut obsolète et non conforme à la norme postale en vigueur NF Z 10-011 qui définit cette information comme faisant partie de l'attribut libelleVoie.
  - Extension [streetNameType](http://hl7.org/fhir/extensions/StructureDefinition-iso21090-ADXP-streetNameType.html#root) : The designation given to the street. (e.g. Street, Avenue, Crescent, etc.).
- libelleVoie 
  - Définition ME : Appellation qui est donnée à la voie par les municipalités. Ce libellé figure in extenso ou en abrégé sur les plaques aux différents angles de chaque rue.
  - Extension [streetNameBase ](http://hl7.org/fhir/extensions/StructureDefinition-iso21090-ADXP-streetNameBase.html#root): The base name of a roadway or artery recognized by a municipality (excluding street type and direction)
- lieuDit 
  - Définition ME : Lieu qui porte un nom rappelant une particularité topographique ou historique et qui, souvent, constitue un écart d'une commune 
  - Extension à définir
- mentionDistribution 
  - Définition ME : Mentions particulières de distribution. Il s'agit de mentions identifiant le service proposé par La Poste au destinataire. Ces mentions sont formées d'un libellé et d'un numéro de séparation (exemple : BP 42534). 
  - Extension [postalBox](http://hl7.org/fhir/extensions/StructureDefinition-iso21090-ADXP-postBox.html#root): A numbered box located in a post station.

**Comment by nriss** [comment]
L'usage de l'extension precinct me paraît ok! Qu'en pensez-vous @sdemeyANS @mchaabaoui ? (Il faudrait faire la même chose côté Annuaire)

**Comment by sdemeyANS** [comment]
> L'usage de l'extension precinct me paraît ok! Qu'en pensez-vous @sdemeyANS @mchaabaoui ? (Il faudrait faire la même chose côté Annuaire)

cela me paraît pas mal aussi.
@jcserafini et @PhilippeC-ANS pour info

**Comment by sdemeyANS** [comment]
maj mapping en cours https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/pull/154
